In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('../data/cleaned_data/cleaned_Algerian_forest_fire_data.csv')
df.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,1,6,2012,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,0
1,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,not fire,0
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,not fire,0
4,5,6,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,not fire,0

In [11]:
df.shape

(244, 15)

In [4]:
data = df.drop(['day', 'month', 'year'], axis=1)

In [28]:
df['Classes'].value_counts()

Classes
fire             131
not fire         101
fire               4
fire               2
not fire           2
not fire           1
not fire           1
not fire           1
Name: count, dtype: int64

In [27]:
df.loc[2:5]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
2,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,0
3,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,not fire,0
4,5,6,2012,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,not fire,0
5,6,6,2012,31,67,14,0.0,82.6,5.8,22.2,3.1,7.0,2.5,fire,0

In [22]:
data.head()

NameError: name 'data' is not defined

In [6]:
data['Classes'].value_counts()

Classes
fire             131
not fire         101
fire               4
fire               2
not fire           2
not fire           1
not fire           1
not fire           1
Name: count, dtype: int64

In [7]:
print(data['Classes'].isna().sum())

1

In [8]:
data['Classes'] = data['Classes'].fillna(data['Classes'].mode()[0])

In [9]:
print(data['Classes'].isna().sum())

0

In [10]:
import re
def remove_spaces(column):
    return column.replace(' ', '')

In [11]:
data['Classes'] = data['Classes'].apply(remove_spaces)

In [12]:
data['Classes'].value_counts()

Classes
fire       138
notfire    106
Name: count, dtype: int64

In [13]:
data.head(20)

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,notfire,0
1,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,notfire,0
2,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,notfire,0
3,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,notfire,0
4,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,notfire,0
5,31,67,14,0.0,82.6,5.8,22.2,3.1,7.0,2.5,fire,0
6,33,54,13,0.0,88.2,9.9,30.5,6.4,10.9,7.2,fire,0
7,30,73,15,0.0,86.6,12.1,38.3,5.6,13.5,7.1,fire,0
8,25,88,13,0.2,52.9,7.9,38.8,0.4,10.5,0.3,notfire,0
9,28,79,12,0.0,73.2,9.5,46.3,1.3,12.6,0.9,notfire,0
10,31,65,14,0.0,84.5,12.5,54.3,4.0,15.8,5.6,fire,0
11,26,81,19,0.0,84.0,13.8,61.4,4.8,17.7,7.1,fire,0
12,27,84,21,1.2,50.0,6.7,17.0,0.5,6.7,0.2,notfire,0
13,30,78,20,0.5,59.0,4.6,7.8,1.0,4.4,0.4,notfire,0
14,28,80,17,3.1,49.4,3.0,7.4,0.4,3.0,0.1,notfire,0
15,29,89,13,0.7,36.1,1.7,7.6,0.0,2.2,0.0,notfire,0
16,30,89,16,0.6,37.3,1.1,7.8,0.0,1.6,0.0,notfire,0
17,31,78,14,0.3,56.9,1.9,8.0,0.7,2.4,0.2,notfire,0
18,31,55,16,0.1,79.9,4.5,16.0,2.5,5.3,1.4,notfire,0
19,30,80,16,0.4,59.8,3.4,27.1,0.9,5.1,0.4,notfire,0

In [14]:
data['Classes']=np.where(data['Classes'].str.contains('notfire'),0,1)

In [15]:
data.head(20)

,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
0,29,57,18,0.0,65.7,3.4,7.6,1.3,3.4,0.5,0,0
1,29,61,13,1.3,64.4,4.1,7.6,1.0,3.9,0.4,0,0
2,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,0,0
3,25,89,13,2.5,28.6,1.3,6.9,0.0,1.7,0.0,0,0
4,27,77,16,0.0,64.8,3.0,14.2,1.2,3.9,0.5,0,0
5,31,67,14,0.0,82.6,5.8,22.2,3.1,7.0,2.5,1,0
6,33,54,13,0.0,88.2,9.9,30.5,6.4,10.9,7.2,1,0
7,30,73,15,0.0,86.6,12.1,38.3,5.6,13.5,7.1,1,0
8,25,88,13,0.2,52.9,7.9,38.8,0.4,10.5,0.3,0,0
9,28,79,12,0.0,73.2,9.5,46.3,1.3,12.6,0.9,0,0
10,31,65,14,0.0,84.5,12.5,54.3,4.0,15.8,5.6,1,0
11,26,81,19,0.0,84.0,13.8,61.4,4.8,17.7,7.1,1,0
12,27,84,21,1.2,50.0,6.7,17.0,0.5,6.7,0.2,0,0
13,30,78,20,0.5,59.0,4.6,7.8,1.0,4.4,0.4,0,0
14,28,80,17,3.1,49.4,3.0,7.4,0.4,3.0,0.1,0,0
15,29,89,13,0.7,36.1,1.7,7.6,0.0,2.2,0.0,0,0
16,30,89,16,0.6,37.3,1.1,7.8,0.0,1.6,0.0,0,0
17,31,78,14,0.3,56.9,1.9,8.0,0.7,2.4,0.2,0,0
18,31,55,16,0.1,79.9,4.5,16.0,2.5,5.3,1.4,0,0
19,30,80,16,0.4,59.8,3.4,27.1,0.9,5.1,0.4,0,0

In [16]:
data.to_csv('../data/processed_data/processed_Algerian_forest_fire_data.csv', index=False)